// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as protos from '../protos/protos';
import * as assert from 'assert';
import * as sinon from 'sinon';
import {SinonStub} from 'sinon';
import {describe, it} from 'mocha';
import * as secretmanagerserviceModule from '../src';

import {PassThrough} from 'stream';

import {protobuf, LocationProtos} from 'google-gax';

// Dynamically loaded proto JSON is needed to get the type information
// to fill in default values for request objects
const root = protobuf.Root.fromJSON(
  require('../protos/protos.json')
).resolveAll();

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function getTypeDefaultValue(typeName: string, fields: string[]) {
  let type = root.lookupType(typeName) as protobuf.Type;
  for (const field of fields.slice(0, -1)) {
    type = type.fields[field]?.resolvedType as protobuf.Type;
  }
  return type.fields[fields[fields.length - 1]]?.defaultValue;
}

function generateSampleMessage<T extends object>(instance: T) {
  const filledObject = (
    instance.constructor as typeof protobuf.Message
  ).toObject(instance as protobuf.Message<T>, {defaults: true});
  return (instance.constructor as typeof protobuf.Message).fromObject(
    filledObject
  ) as T;
}

function stubSimpleCall<ResponseType>(response?: ResponseType, error?: Error) {
  return error
    ? sinon.stub().rejects(error)
    : sinon.stub().resolves([response]);
}

function stubSimpleCallWithCallback<ResponseType>(
  response?: ResponseType,
  error?: Error
) {
  return error
    ? sinon.stub().callsArgWith(2, error)
    : sinon.stub().callsArgWith(2, null, response);
}

function stubPageStreamingCall<ResponseType>(
  responses?: ResponseType[],
  error?: Error
) {
  const pagingStub = sinon.stub();
  if (responses) {
    for (let i = 0; i < responses.length; ++i) {
      pagingStub.onCall(i).callsArgWith(2, null, responses[i]);
    }
  }
  const transformStub = error
    ? sinon.stub().callsArgWith(2, error)
    : pagingStub;
  const mockStream = new PassThrough({
    objectMode: true,
    transform: transformStub,
  });
  // trigger as many responses as needed
  if (responses) {
    for (let i = 0; i < responses.length; ++i) {
      setImmediate(() => {
        mockStream.write({});
      });
    }
    setImmediate(() => {
      mockStream.end();
    });
  } else {
    setImmediate(() => {
      mockStream.write({});
    });
    setImmediate(() => {
      mockStream.end();
    });
  }
  return sinon.stub().returns(mockStream);
}

function stubAsyncIterationCall<ResponseType>(
  responses?: ResponseType[],
  error?: Error
) {
  let counter = 0;
  const asyncIterable = {
    [Symbol.asyncIterator]() {
      return {
        async next() {
          if (error) {
            return Promise.reject(error);
          }
          if (counter >= responses!.length) {
            return Promise.resolve({done: true, value: undefined});
          }
          return Promise.resolve({done: false, value: responses![counter++]});
        },
      };
    },
  };
  return sinon.stub().returns(asyncIterable);
}

describe('v1.SecretManagerServiceClient', () => {
  describe('Common methods', () => {
    it('has apiEndpoint', () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient();
      const apiEndpoint = client.apiEndpoint;
      assert.strictEqual(apiEndpoint, 'secretmanager.googleapis.com');
    });

    it('has universeDomain', () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient();
      const universeDomain = client.universeDomain;
      assert.strictEqual(universeDomain, 'googleapis.com');
    });

    if (
      typeof process === 'object' &&
      typeof process.emitWarning === 'function'
    ) {
      it('throws DeprecationWarning if static servicePath is used', () => {
        const stub = sinon.stub(process, 'emitWarning');
        const servicePath =
          secretmanagerserviceModule.v1.SecretManagerServiceClient.servicePath;
        assert.strictEqual(servicePath, 'secretmanager.googleapis.com');
        assert(stub.called);
        stub.restore();
      });

      it('throws DeprecationWarning if static apiEndpoint is used', () => {
        const stub = sinon.stub(process, 'emitWarning');
        const apiEndpoint =
          secretmanagerserviceModule.v1.SecretManagerServiceClient.apiEndpoint;
        assert.strictEqual(apiEndpoint, 'secretmanager.googleapis.com');
        assert(stub.called);
        stub.restore();
      });
    }
    it('sets apiEndpoint according to universe domain camelCase', () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          universeDomain: 'example.com',
        });
      const servicePath = client.apiEndpoint;
      assert.strictEqual(servicePath, 'secretmanager.example.com');
    });

    it('sets apiEndpoint according to universe domain snakeCase', () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          universe_domain: 'example.com',
        });
      const servicePath = client.apiEndpoint;
      assert.strictEqual(servicePath, 'secretmanager.example.com');
    });

    if (typeof process === 'object' && 'env' in process) {
      describe('GOOGLE_CLOUD_UNIVERSE_DOMAIN environment variable', () => {
        it('sets apiEndpoint from environment variable', () => {
          const saved = process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'];
          process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'] = 'example.com';
          const client =
            new secretmanagerserviceModule.v1.SecretManagerServiceClient();
          const servicePath = client.apiEndpoint;
          assert.strictEqual(servicePath, 'secretmanager.example.com');
          if (saved) {
            process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'] = saved;
          } else {
            delete process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'];
          }
        });

        it('value configured in code has priority over environment variable', () => {
          const saved = process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'];
          process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'] = 'example.com';
          const client =
            new secretmanagerserviceModule.v1.SecretManagerServiceClient({
              universeDomain: 'configured.example.com',
            });
          const servicePath = client.apiEndpoint;
          assert.strictEqual(
            servicePath,
            'secretmanager.configured.example.com'
          );
          if (saved) {
            process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'] = saved;
          } else {
            delete process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'];
          }
        });
      });
    }
    it('does not allow setting both universeDomain and universe_domain', () => {
      assert.throws(() => {
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          universe_domain: 'example.com',
          universeDomain: 'example.net',
        });
      });
    });

    it('has port', () => {
      const port =
        secretmanagerserviceModule.v1.SecretManagerServiceClient.port;
      assert(port);
      assert(typeof port === 'number');
    });

    it('should create a client with no option', () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient();
      assert(client);
    });

    it('should create a client with gRPC fallback', () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          fallback: true,
        });
      assert(client);
    });

    it('has initialize method and supports deferred initialization', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      assert.strictEqual(client.secretManagerServiceStub, undefined);
      await client.initialize();
      assert(client.secretManagerServiceStub);
    });

    it('has close method for the initialized client', done => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      assert(client.secretManagerServiceStub);
      client.close().then(() => {
        done();
      });
    });

    it('has close method for the non-initialized client', done => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      assert.strictEqual(client.secretManagerServiceStub, undefined);
      client.close().then(() => {
        done();
      });
    });

    it('has getProjectId method', async () => {
      const fakeProjectId = 'fake-project-id';
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.auth.getProjectId = sinon.stub().resolves(fakeProjectId);
      const result = await client.getProjectId();
      assert.strictEqual(result, fakeProjectId);
      assert((client.auth.getProjectId as SinonStub).calledWithExactly());
    });

    it('has getProjectId method with callback', async () => {
      const fakeProjectId = 'fake-project-id';
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.auth.getProjectId = sinon
        .stub()
        .callsArgWith(0, null, fakeProjectId);
      const promise = new Promise((resolve, reject) => {
        client.getProjectId((err?: Error | null, projectId?: string | null) => {
          if (err) {
            reject(err);
          } else {
            resolve(projectId);
          }
        });
      });
      const result = await promise;
      assert.strictEqual(result, fakeProjectId);
    });
  });

  describe('createSecret', () => {
    it('invokes createSecret without error', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.CreateSecretRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.CreateSecretRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.Secret()
      );
      client.innerApiCalls.createSecret = stubSimpleCall(expectedResponse);
      const [response] = await client.createSecret(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.createSecret as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.createSecret as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes createSecret without error using callback', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.CreateSecretRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.CreateSecretRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.Secret()
      );
      client.innerApiCalls.createSecret =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.createSecret(
          request,
          (
            err?: Error | null,
            result?: protos.google.cloud.secretmanager.v1.ISecret | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.createSecret as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.createSecret as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes createSecret with error', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.CreateSecretRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.CreateSecretRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.createSecret = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(client.createSecret(request), expectedError);
      const actualRequest = (
        client.innerApiCalls.createSecret as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.createSecret as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes createSecret with closed client', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.CreateSecretRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.CreateSecretRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedError = new Error('The client has already been closed.');
      client.close();
      await assert.rejects(client.createSecret(request), expectedError);
    });
  });

  describe('addSecretVersion', () => {
    it('invokes addSecretVersion without error', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.AddSecretVersionRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.AddSecretVersionRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.SecretVersion()
      );
      client.innerApiCalls.addSecretVersion = stubSimpleCall(expectedResponse);
      const [response] = await client.addSecretVersion(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.addSecretVersion as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.addSecretVersion as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes addSecretVersion without error using callback', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.AddSecretVersionRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.AddSecretVersionRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.SecretVersion()
      );
      client.innerApiCalls.addSecretVersion =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.addSecretVersion(
          request,
          (
            err?: Error | null,
            result?: protos.google.cloud.secretmanager.v1.ISecretVersion | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.addSecretVersion as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.addSecretVersion as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes addSecretVersion with error', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.AddSecretVersionRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.AddSecretVersionRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.addSecretVersion = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(client.addSecretVersion(request), expectedError);
      const actualRequest = (
        client.innerApiCalls.addSecretVersion as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.addSecretVersion as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes addSecretVersion with closed client', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.AddSecretVersionRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.AddSecretVersionRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedError = new Error('The client has already been closed.');
      client.close();
      await assert.rejects(client.addSecretVersion(request), expectedError);
    });
  });

  describe('getSecret', () => {
    it('invokes getSecret without error', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.GetSecretRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.GetSecretRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.Secret()
      );
      client.innerApiCalls.getSecret = stubSimpleCall(expectedResponse);
      const [response] = await client.getSecret(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.getSecret as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.getSecret as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes getSecret without error using callback', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.GetSecretRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.GetSecretRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.Secret()
      );
      client.innerApiCalls.getSecret =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.getSecret(
          request,
          (
            err?: Error | null,
            result?: protos.google.cloud.secretmanager.v1.ISecret | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.getSecret as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.getSecret as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes getSecret with error', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.GetSecretRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.GetSecretRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.getSecret = stubSimpleCall(undefined, expectedError);
      await assert.rejects(client.getSecret(request), expectedError);
      const actualRequest = (
        client.innerApiCalls.getSecret as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.getSecret as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes getSecret with closed client', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.GetSecretRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.GetSecretRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedError = new Error('The client has already been closed.');
      client.close();
      await assert.rejects(client.getSecret(request), expectedError);
    });
  });

  describe('updateSecret', () => {
    it('invokes updateSecret without error', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.UpdateSecretRequest()
      );
      request.secret ??= {};
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.UpdateSecretRequest',
        ['secret', 'name']
      );
      request.secret.name = defaultValue1;
      const expectedHeaderRequestParams = `secret.name=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.Secret()
      );
      client.innerApiCalls.updateSecret = stubSimpleCall(expectedResponse);
      const [response] = await client.updateSecret(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.updateSecret as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.updateSecret as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes updateSecret without error using callback', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.UpdateSecretRequest()
      );
      request.secret ??= {};
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.UpdateSecretRequest',
        ['secret', 'name']
      );
      request.secret.name = defaultValue1;
      const expectedHeaderRequestParams = `secret.name=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.Secret()
      );
      client.innerApiCalls.updateSecret =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.updateSecret(
          request,
          (
            err?: Error | null,
            result?: protos.google.cloud.secretmanager.v1.ISecret | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.updateSecret as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.updateSecret as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes updateSecret with error', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.UpdateSecretRequest()
      );
      request.secret ??= {};
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.UpdateSecretRequest',
        ['secret', 'name']
      );
      request.secret.name = defaultValue1;
      const expectedHeaderRequestParams = `secret.name=${defaultValue1}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.updateSecret = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(client.updateSecret(request), expectedError);
      const actualRequest = (
        client.innerApiCalls.updateSecret as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.updateSecret as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes updateSecret with closed client', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.UpdateSecretRequest()
      );
      request.secret ??= {};
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.UpdateSecretRequest',
        ['secret', 'name']
      );
      request.secret.name = defaultValue1;
      const expectedError = new Error('The client has already been closed.');
      client.close();
      await assert.rejects(client.updateSecret(request), expectedError);
    });
  });

  describe('deleteSecret', () => {
    it('invokes deleteSecret without error', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.DeleteSecretRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.DeleteSecretRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.protobuf.Empty()
      );
      client.innerApiCalls.deleteSecret = stubSimpleCall(expectedResponse);
      const [response] = await client.deleteSecret(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.deleteSecret as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.deleteSecret as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes deleteSecret without error using callback', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.DeleteSecretRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.DeleteSecretRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.protobuf.Empty()
      );
      client.innerApiCalls.deleteSecret =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.deleteSecret(
          request,
          (
            err?: Error | null,
            result?: protos.google.protobuf.IEmpty | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.deleteSecret as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.deleteSecret as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes deleteSecret with error', async () => {
      const client =
        new secretmanagerserviceModule.v1.SecretManagerServiceClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.secretmanager.v1.DeleteSecretRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.secretmanager.v1.DeleteSecretRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.deleteSecret = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(client.deleteSecret(request), expectedError);
      const actualRequest = (
        client.innerApiCalls.deleteSecret as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.deleteSecret as SinonStub
      ).getCall(0).args[1].other