// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as protos from '../protos/protos';
import * as assert from 'assert';
import * as sinon from 'sinon';
import {SinonStub} from 'sinon';
import {describe, it} from 'mocha';
import * as sessionentitytypesModule from '../src';

import {PassThrough} from 'stream';

import {protobuf, LocationProtos} from 'google-gax';

// Dynamically loaded proto JSON is needed to get the type information
// to fill in default values for request objects
const root = protobuf.Root.fromJSON(
  require('../protos/protos.json')
).resolveAll();

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function getTypeDefaultValue(typeName: string, fields: string[]) {
  let type = root.lookupType(typeName) as protobuf.Type;
  for (const field of fields.slice(0, -1)) {
    type = type.fields[field]?.resolvedType as protobuf.Type;
  }
  return type.fields[fields[fields.length - 1]]?.defaultValue;
}

function generateSampleMessage<T extends object>(instance: T) {
  const filledObject = (
    instance.constructor as typeof protobuf.Message
  ).toObject(instance as protobuf.Message<T>, {defaults: true});
  return (instance.constructor as typeof protobuf.Message).fromObject(
    filledObject
  ) as T;
}

function stubSimpleCall<ResponseType>(response?: ResponseType, error?: Error) {
  return error
    ? sinon.stub().rejects(error)
    : sinon.stub().resolves([response]);
}

function stubSimpleCallWithCallback<ResponseType>(
  response?: ResponseType,
  error?: Error
) {
  return error
    ? sinon.stub().callsArgWith(2, error)
    : sinon.stub().callsArgWith(2, null, response);
}

function stubPageStreamingCall<ResponseType>(
  responses?: ResponseType[],
  error?: Error
) {
  const pagingStub = sinon.stub();
  if (responses) {
    for (let i = 0; i < responses.length; ++i) {
      pagingStub.onCall(i).callsArgWith(2, null, responses[i]);
    }
  }
  const transformStub = error
    ? sinon.stub().callsArgWith(2, error)
    : pagingStub;
  const mockStream = new PassThrough({
    objectMode: true,
    transform: transformStub,
  });
  // trigger as many responses as needed
  if (responses) {
    for (let i = 0; i < responses.length; ++i) {
      setImmediate(() => {
        mockStream.write({});
      });
    }
    setImmediate(() => {
      mockStream.end();
    });
  } else {
    setImmediate(() => {
      mockStream.write({});
    });
    setImmediate(() => {
      mockStream.end();
    });
  }
  return sinon.stub().returns(mockStream);
}

function stubAsyncIterationCall<ResponseType>(
  responses?: ResponseType[],
  error?: Error
) {
  let counter = 0;
  const asyncIterable = {
    [Symbol.asyncIterator]() {
      return {
        async next() {
          if (error) {
            return Promise.reject(error);
          }
          if (counter >= responses!.length) {
            return Promise.resolve({done: true, value: undefined});
          }
          return Promise.resolve({done: false, value: responses![counter++]});
        },
      };
    },
  };
  return sinon.stub().returns(asyncIterable);
}

describe('v2beta1.SessionEntityTypesClient', () => {
  describe('Common methods', () => {
    it('has apiEndpoint', () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient();
      const apiEndpoint = client.apiEndpoint;
      assert.strictEqual(apiEndpoint, 'dialogflow.googleapis.com');
    });

    it('has universeDomain', () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient();
      const universeDomain = client.universeDomain;
      assert.strictEqual(universeDomain, 'googleapis.com');
    });

    if (
      typeof process === 'object' &&
      typeof process.emitWarning === 'function'
    ) {
      it('throws DeprecationWarning if static servicePath is used', () => {
        const stub = sinon.stub(process, 'emitWarning');
        const servicePath =
          sessionentitytypesModule.v2beta1.SessionEntityTypesClient.servicePath;
        assert.strictEqual(servicePath, 'dialogflow.googleapis.com');
        assert(stub.called);
        stub.restore();
      });

      it('throws DeprecationWarning if static apiEndpoint is used', () => {
        const stub = sinon.stub(process, 'emitWarning');
        const apiEndpoint =
          sessionentitytypesModule.v2beta1.SessionEntityTypesClient.apiEndpoint;
        assert.strictEqual(apiEndpoint, 'dialogflow.googleapis.com');
        assert(stub.called);
        stub.restore();
      });
    }
    it('sets apiEndpoint according to universe domain camelCase', () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          universeDomain: 'example.com',
        });
      const servicePath = client.apiEndpoint;
      assert.strictEqual(servicePath, 'dialogflow.example.com');
    });

    it('sets apiEndpoint according to universe domain snakeCase', () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          universe_domain: 'example.com',
        });
      const servicePath = client.apiEndpoint;
      assert.strictEqual(servicePath, 'dialogflow.example.com');
    });

    if (typeof process === 'object' && 'env' in process) {
      describe('GOOGLE_CLOUD_UNIVERSE_DOMAIN environment variable', () => {
        it('sets apiEndpoint from environment variable', () => {
          const saved = process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'];
          process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'] = 'example.com';
          const client =
            new sessionentitytypesModule.v2beta1.SessionEntityTypesClient();
          const servicePath = client.apiEndpoint;
          assert.strictEqual(servicePath, 'dialogflow.example.com');
          if (saved) {
            process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'] = saved;
          } else {
            delete process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'];
          }
        });

        it('value configured in code has priority over environment variable', () => {
          const saved = process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'];
          process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'] = 'example.com';
          const client =
            new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
              universeDomain: 'configured.example.com',
            });
          const servicePath = client.apiEndpoint;
          assert.strictEqual(servicePath, 'dialogflow.configured.example.com');
          if (saved) {
            process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'] = saved;
          } else {
            delete process.env['GOOGLE_CLOUD_UNIVERSE_DOMAIN'];
          }
        });
      });
    }
    it('does not allow setting both universeDomain and universe_domain', () => {
      assert.throws(() => {
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          universe_domain: 'example.com',
          universeDomain: 'example.net',
        });
      });
    });

    it('has port', () => {
      const port =
        sessionentitytypesModule.v2beta1.SessionEntityTypesClient.port;
      assert(port);
      assert(typeof port === 'number');
    });

    it('should create a client with no option', () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient();
      assert(client);
    });

    it('should create a client with gRPC fallback', () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          fallback: true,
        });
      assert(client);
    });

    it('has initialize method and supports deferred initialization', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      assert.strictEqual(client.sessionEntityTypesStub, undefined);
      await client.initialize();
      assert(client.sessionEntityTypesStub);
    });

    it('has close method for the initialized client', done => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      assert(client.sessionEntityTypesStub);
      client.close().then(() => {
        done();
      });
    });

    it('has close method for the non-initialized client', done => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      assert.strictEqual(client.sessionEntityTypesStub, undefined);
      client.close().then(() => {
        done();
      });
    });

    it('has getProjectId method', async () => {
      const fakeProjectId = 'fake-project-id';
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.auth.getProjectId = sinon.stub().resolves(fakeProjectId);
      const result = await client.getProjectId();
      assert.strictEqual(result, fakeProjectId);
      assert((client.auth.getProjectId as SinonStub).calledWithExactly());
    });

    it('has getProjectId method with callback', async () => {
      const fakeProjectId = 'fake-project-id';
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.auth.getProjectId = sinon
        .stub()
        .callsArgWith(0, null, fakeProjectId);
      const promise = new Promise((resolve, reject) => {
        client.getProjectId((err?: Error | null, projectId?: string | null) => {
          if (err) {
            reject(err);
          } else {
            resolve(projectId);
          }
        });
      });
      const result = await promise;
      assert.strictEqual(result, fakeProjectId);
    });
  });

  describe('getSessionEntityType', () => {
    it('invokes getSessionEntityType without error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.GetSessionEntityTypeRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.GetSessionEntityTypeRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
      );
      client.innerApiCalls.getSessionEntityType =
        stubSimpleCall(expectedResponse);
      const [response] = await client.getSessionEntityType(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.getSessionEntityType as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.getSessionEntityType as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes getSessionEntityType without error using callback', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.GetSessionEntityTypeRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.GetSessionEntityTypeRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
      );
      client.innerApiCalls.getSessionEntityType =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.getSessionEntityType(
          request,
          (
            err?: Error | null,
            result?: protos.google.cloud.dialogflow.v2beta1.ISessionEntityType | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.getSessionEntityType as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.getSessionEntityType as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes getSessionEntityType with error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.GetSessionEntityTypeRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.GetSessionEntityTypeRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.getSessionEntityType = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(client.getSessionEntityType(request), expectedError);
      const actualRequest = (
        client.innerApiCalls.getSessionEntityType as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.getSessionEntityType as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes getSessionEntityType with closed client', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.GetSessionEntityTypeRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.GetSessionEntityTypeRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedError = new Error('The client has already been closed.');
      client.close();
      await assert.rejects(client.getSessionEntityType(request), expectedError);
    });
  });

  describe('createSessionEntityType', () => {
    it('invokes createSessionEntityType without error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.CreateSessionEntityTypeRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.CreateSessionEntityTypeRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
      );
      client.innerApiCalls.createSessionEntityType =
        stubSimpleCall(expectedResponse);
      const [response] = await client.createSessionEntityType(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.createSessionEntityType as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.createSessionEntityType as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes createSessionEntityType without error using callback', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.CreateSessionEntityTypeRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.CreateSessionEntityTypeRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
      );
      client.innerApiCalls.createSessionEntityType =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.createSessionEntityType(
          request,
          (
            err?: Error | null,
            result?: protos.google.cloud.dialogflow.v2beta1.ISessionEntityType | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.createSessionEntityType as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.createSessionEntityType as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes createSessionEntityType with error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.CreateSessionEntityTypeRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.CreateSessionEntityTypeRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.createSessionEntityType = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(
        client.createSessionEntityType(request),
        expectedError
      );
      const actualRequest = (
        client.innerApiCalls.createSessionEntityType as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.createSessionEntityType as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes createSessionEntityType with closed client', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.CreateSessionEntityTypeRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.CreateSessionEntityTypeRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedError = new Error('The client has already been closed.');
      client.close();
      await assert.rejects(
        client.createSessionEntityType(request),
        expectedError
      );
    });
  });

  describe('updateSessionEntityType', () => {
    it('invokes updateSessionEntityType without error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.UpdateSessionEntityTypeRequest()
      );
      request.sessionEntityType ??= {};
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.UpdateSessionEntityTypeRequest',
        ['sessionEntityType', 'name']
      );
      request.sessionEntityType.name = defaultValue1;
      const expectedHeaderRequestParams = `session_entity_type.name=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
      );
      client.innerApiCalls.updateSessionEntityType =
        stubSimpleCall(expectedResponse);
      const [response] = await client.updateSessionEntityType(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.updateSessionEntityType as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.updateSessionEntityType as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes updateSessionEntityType without error using callback', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.UpdateSessionEntityTypeRequest()
      );
      request.sessionEntityType ??= {};
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.UpdateSessionEntityTypeRequest',
        ['sessionEntityType', 'name']
      );
      request.sessionEntityType.name = defaultValue1;
      const expectedHeaderRequestParams = `session_entity_type.name=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
      );
      client.innerApiCalls.updateSessionEntityType =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.updateSessionEntityType(
          request,
          (
            err?: Error | null,
            result?: protos.google.cloud.dialogflow.v2beta1.ISessionEntityType | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.updateSessionEntityType as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.updateSessionEntityType as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes updateSessionEntityType with error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.UpdateSessionEntityTypeRequest()
      );
      request.sessionEntityType ??= {};
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.UpdateSessionEntityTypeRequest',
        ['sessionEntityType', 'name']
      );
      request.sessionEntityType.name = defaultValue1;
      const expectedHeaderRequestParams = `session_entity_type.name=${defaultValue1}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.updateSessionEntityType = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(
        client.updateSessionEntityType(request),
        expectedError
      );
      const actualRequest = (
        client.innerApiCalls.updateSessionEntityType as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.updateSessionEntityType as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes updateSessionEntityType with closed client', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.UpdateSessionEntityTypeRequest()
      );
      request.sessionEntityType ??= {};
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.UpdateSessionEntityTypeRequest',
        ['sessionEntityType', 'name']
      );
      request.sessionEntityType.name = defaultValue1;
      const expectedError = new Error('The client has already been closed.');
      client.close();
      await assert.rejects(
        client.updateSessionEntityType(request),
        expectedError
      );
    });
  });

  describe('deleteSessionEntityType', () => {
    it('invokes deleteSessionEntityType without error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.DeleteSessionEntityTypeRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.DeleteSessionEntityTypeRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.protobuf.Empty()
      );
      client.innerApiCalls.deleteSessionEntityType =
        stubSimpleCall(expectedResponse);
      const [response] = await client.deleteSessionEntityType(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.deleteSessionEntityType as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.deleteSessionEntityType as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes deleteSessionEntityType without error using callback', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.DeleteSessionEntityTypeRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.DeleteSessionEntityTypeRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1}`;
      const expectedResponse = generateSampleMessage(
        new protos.google.protobuf.Empty()
      );
      client.innerApiCalls.deleteSessionEntityType =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.deleteSessionEntityType(
          request,
          (
            err?: Error | null,
            result?: protos.google.protobuf.IEmpty | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.deleteSessionEntityType as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.deleteSessionEntityType as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes deleteSessionEntityType with error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.DeleteSessionEntityTypeRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.DeleteSessionEntityTypeRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedHeaderRequestParams = `name=${defaultValue1}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.deleteSessionEntityType = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(
        client.deleteSessionEntityType(request),
        expectedError
      );
      const actualRequest = (
        client.innerApiCalls.deleteSessionEntityType as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.deleteSessionEntityType as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes deleteSessionEntityType with closed client', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.DeleteSessionEntityTypeRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.DeleteSessionEntityTypeRequest',
        ['name']
      );
      request.name = defaultValue1;
      const expectedError = new Error('The client has already been closed.');
      client.close();
      await assert.rejects(
        client.deleteSessionEntityType(request),
        expectedError
      );
    });
  });

  describe('listSessionEntityTypes', () => {
    it('invokes listSessionEntityTypes without error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedResponse = [
        generateSampleMessage(
          new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
        ),
        generateSampleMessage(
          new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
        ),
        generateSampleMessage(
          new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
        ),
      ];
      client.innerApiCalls.listSessionEntityTypes =
        stubSimpleCall(expectedResponse);
      const [response] = await client.listSessionEntityTypes(request);
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.listSessionEntityTypes as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.listSessionEntityTypes as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes listSessionEntityTypes without error using callback', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedResponse = [
        generateSampleMessage(
          new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
        ),
        generateSampleMessage(
          new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
        ),
        generateSampleMessage(
          new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
        ),
      ];
      client.innerApiCalls.listSessionEntityTypes =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.listSessionEntityTypes(
          request,
          (
            err?: Error | null,
            result?:
              | protos.google.cloud.dialogflow.v2beta1.ISessionEntityType[]
              | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      const actualRequest = (
        client.innerApiCalls.listSessionEntityTypes as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.listSessionEntityTypes as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes listSessionEntityTypes with error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedError = new Error('expected');
      client.innerApiCalls.listSessionEntityTypes = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(
        client.listSessionEntityTypes(request),
        expectedError
      );
      const actualRequest = (
        client.innerApiCalls.listSessionEntityTypes as SinonStub
      ).getCall(0).args[0];
      assert.deepStrictEqual(actualRequest, request);
      const actualHeaderRequestParams = (
        client.innerApiCalls.listSessionEntityTypes as SinonStub
      ).getCall(0).args[1].otherArgs.headers['x-goog-request-params'];
      assert(actualHeaderRequestParams.includes(expectedHeaderRequestParams));
    });

    it('invokes listSessionEntityTypesStream without error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedResponse = [
        generateSampleMessage(
          new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
        ),
        generateSampleMessage(
          new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
        ),
        generateSampleMessage(
          new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
        ),
      ];
      client.descriptors.page.listSessionEntityTypes.createStream =
        stubPageStreamingCall(expectedResponse);
      const stream = client.listSessionEntityTypesStream(request);
      const promise = new Promise((resolve, reject) => {
        const responses: protos.google.cloud.dialogflow.v2beta1.SessionEntityType[] =
          [];
        stream.on(
          'data',
          (
            response: protos.google.cloud.dialogflow.v2beta1.SessionEntityType
          ) => {
            responses.push(response);
          }
        );
        stream.on('end', () => {
          resolve(responses);
        });
        stream.on('error', (err: Error) => {
          reject(err);
        });
      });
      const responses = await promise;
      assert.deepStrictEqual(responses, expectedResponse);
      assert(
        (
          client.descriptors.page.listSessionEntityTypes
            .createStream as SinonStub
        )
          .getCall(0)
          .calledWith(client.innerApiCalls.listSessionEntityTypes, request)
      );
      assert(
        (
          client.descriptors.page.listSessionEntityTypes
            .createStream as SinonStub
        )
          .getCall(0)
          .args[2].otherArgs.headers['x-goog-request-params'].includes(
            expectedHeaderRequestParams
          )
      );
    });

    it('invokes listSessionEntityTypesStream with error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedError = new Error('expected');
      client.descriptors.page.listSessionEntityTypes.createStream =
        stubPageStreamingCall(undefined, expectedError);
      const stream = client.listSessionEntityTypesStream(request);
      const promise = new Promise((resolve, reject) => {
        const responses: protos.google.cloud.dialogflow.v2beta1.SessionEntityType[] =
          [];
        stream.on(
          'data',
          (
            response: protos.google.cloud.dialogflow.v2beta1.SessionEntityType
          ) => {
            responses.push(response);
          }
        );
        stream.on('end', () => {
          resolve(responses);
        });
        stream.on('error', (err: Error) => {
          reject(err);
        });
      });
      await assert.rejects(promise, expectedError);
      assert(
        (
          client.descriptors.page.listSessionEntityTypes
            .createStream as SinonStub
        )
          .getCall(0)
          .calledWith(client.innerApiCalls.listSessionEntityTypes, request)
      );
      assert(
        (
          client.descriptors.page.listSessionEntityTypes
            .createStream as SinonStub
        )
          .getCall(0)
          .args[2].otherArgs.headers['x-goog-request-params'].includes(
            expectedHeaderRequestParams
          )
      );
    });

    it('uses async iteration with listSessionEntityTypes without error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedResponse = [
        generateSampleMessage(
          new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
        ),
        generateSampleMessage(
          new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
        ),
        generateSampleMessage(
          new protos.google.cloud.dialogflow.v2beta1.SessionEntityType()
        ),
      ];
      client.descriptors.page.listSessionEntityTypes.asyncIterate =
        stubAsyncIterationCall(expectedResponse);
      const responses: protos.google.cloud.dialogflow.v2beta1.ISessionEntityType[] =
        [];
      const iterable = client.listSessionEntityTypesAsync(request);
      for await (const resource of iterable) {
        responses.push(resource!);
      }
      assert.deepStrictEqual(responses, expectedResponse);
      assert.deepStrictEqual(
        (
          client.descriptors.page.listSessionEntityTypes
            .asyncIterate as SinonStub
        ).getCall(0).args[1],
        request
      );
      assert(
        (
          client.descriptors.page.listSessionEntityTypes
            .asyncIterate as SinonStub
        )
          .getCall(0)
          .args[2].otherArgs.headers['x-goog-request-params'].includes(
            expectedHeaderRequestParams
          )
      );
    });

    it('uses async iteration with listSessionEntityTypes with error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new protos.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest()
      );
      const defaultValue1 = getTypeDefaultValue(
        '.google.cloud.dialogflow.v2beta1.ListSessionEntityTypesRequest',
        ['parent']
      );
      request.parent = defaultValue1;
      const expectedHeaderRequestParams = `parent=${defaultValue1}`;
      const expectedError = new Error('expected');
      client.descriptors.page.listSessionEntityTypes.asyncIterate =
        stubAsyncIterationCall(undefined, expectedError);
      const iterable = client.listSessionEntityTypesAsync(request);
      await assert.rejects(async () => {
        const responses: protos.google.cloud.dialogflow.v2beta1.ISessionEntityType[] =
          [];
        for await (const resource of iterable) {
          responses.push(resource!);
        }
      });
      assert.deepStrictEqual(
        (
          client.descriptors.page.listSessionEntityTypes
            .asyncIterate as SinonStub
        ).getCall(0).args[1],
        request
      );
      assert(
        (
          client.descriptors.page.listSessionEntityTypes
            .asyncIterate as SinonStub
        )
          .getCall(0)
          .args[2].otherArgs.headers['x-goog-request-params'].includes(
            expectedHeaderRequestParams
          )
      );
    });
  });
  describe('getLocation', () => {
    it('invokes getLocation without error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new LocationProtos.google.cloud.location.GetLocationRequest()
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new LocationProtos.google.cloud.location.Location()
      );
      client.locationsClient.getLocation = stubSimpleCall(expectedResponse);
      const response = await client.getLocation(request, expectedOptions);
      assert.deepStrictEqual(response, [expectedResponse]);
      assert(
        (client.locationsClient.getLocation as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });
    it('invokes getLocation without error using callback', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new LocationProtos.google.cloud.location.GetLocationRequest()
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new LocationProtos.google.cloud.location.Location()
      );
      client.locationsClient.getLocation = sinon
        .stub()
        .callsArgWith(2, null, expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.getLocation(
          request,
          expectedOptions,
          (
            err?: Error | null,
            result?: LocationProtos.google.cloud.location.ILocation | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      assert((client.locationsClient.getLocation as SinonStub).getCall(0));
    });
    it('invokes getLocation with error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new LocationProtos.google.cloud.location.GetLocationRequest()
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedError = new Error('expected');
      client.locationsClient.getLocation = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(
        client.getLocation(request, expectedOptions),
        expectedError
      );
      assert(
        (client.locationsClient.getLocation as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });
  });
  describe('listLocationsAsync', () => {
    it('uses async iteration with listLocations without error', async () => {
      const client =
        new sessionentitytypesModule.v2beta1.SessionEntityTypesClient({
          credentials: {client_email: 'bogus', private_key: 'bogus'},
          projectId: 'bogus',
        });
      client.initialize();
      const request = generateSampleMessage(
        new LocationProtos.google.cloud.location.ListLocationsRequest()
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedResponse = [
        generateSampleMessage(
          new LocationProtos.google.cloud.location.Location()
        ),
        generateSampleMessage(
          new LocationProtos.google.cloud.location.Location()
        ),
        generateSampleMessage(
          new LocationProtos.google.cloud.location.Location()
        ),
      ];
      client.locationsClient.descriptors.page.listLocations.asyncIterate =
        stubAsyncIterationCall(expectedResponse);
      const responses: LocationProtos.google.cloud.location.ILocation[] = [];
      const iterable = client.listLocationsAsync(request);
      for await (const resource of iterable) {
        responses.push(resource!);
      }
      assert.deepStrictEqual(responses, expectedResponse);
      assert.deepStrictEqual(
        (
          client.locationsClient.descriptors.page.listLocations
            .asyncIterate as SinonStub
        ).getCall(0).args[1],
        request
      );
      assert(
        (
          client.locationsClient.descriptors.page.listLocations
            .asyncIterate as SinonStub
        )
          .getCall(0)
          .args[2].otherArgs.headers['x-goog-request-params'].includes(
            expectedHeaderRequestParams
          )
      );
    });
    it('uses async iteration with listLocat